
version: '2.1'
services:
  mysql:
    extends:
      file: docker-compose-base.yml
      service: base-mysql
    container_name: ${CONTAINER_HOST_NAME:-standalone.mysql}
    hostname: ${CONTAINER_HOST_NAME:-standalone.mysql}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.mysql}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/mysql/standalone}
    network_mode: bridge
    ports:
    - "${EXTERNAL_MYSQL_3306_PORT:-3306}:3306"
    restart: always
    volumes:
    - data:/var/lib/mysql
    - log:/var/log/mysql

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/log
      o: bind
