
version: '2.1'
services:
  base-mysql:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_APT_MIRROR=${IMAGE_ARG_APT_MIRROR:-mirrors.163.com}
      - IMAGE_ARG_IMAGE_TAG=${IMAGE_ARG_IMAGE_TAG:-5.7.22}
    command: [--character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --init-connect='SET NAMES utf8mb4;', --innodb-flush-log-at-trx-commit=0]
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD:-false} # changeme
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_pass} # changeme
    - MYSQL_USER=${MYSQL_USER:-user} # changeme
    - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user_pass} # changeme
    - MYSQL_DATABASE=${MYSQL_DATABASE:-db}
    image: ${IMAGE_PREFIX:-cloudready/}${IMAGE_NAME:-mysql}:${IMAGE_TAG:-5.7.22-SNAPSHOT}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.mysql}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/mysql/standalone}
    restart: always
