
version: '2.1'
services:
  mysql-develop:
    extends:
      file: docker-compose-base.yml
      service: base-mysql
    container_name: ${CONTAINER_HOST_NAME:-mysql}
    hostname: ${CONTAINER_HOST_NAME:-mysql}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.56}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::56}
    ports:
    - "${SERVER_PORT:-3306}:3306"
    volumes:
    - data:/var/lib/mysql
    - log:/var/log/mysql

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/log
      o: bind
